### ISSUE TITLE
s9s haproxy asks cannot find cluster ID

### ISSUE THREAD

**Issue by umarzuki** [severalnines/s9s-admin#3]
~/s9s-galera-mariadb-3.5.0/mysql/scripts/install/s9s-admin/cluster$ ./s9s_haproxy --install -i 1 -n10.1.1.100,10.1.1.101 -h10.1.1.10 -P3306
No matching configuration file found having cluster_id=1

**Comment by ashraf-s9s** [comment]
s9s_haproxy script is deprecated. Please use ClusterControl UI to deploy HAproxy.
