### ISSUE TITLE
Update s9s_haproxy for CentOS7 and systemd

### ISSUE THREAD

**Issue by MattMencel** [severalnines/s9s-admin#4]
I made a couple local modifications to get the s9s_haproxy script to work on a CentOS7 node.

Not sure if these are exactly correct, but the haproxy script worked for me once I changed them to use systemctl.

```
# cat -n /usr/bin/s9s_haproxy  | grep systemctl
   813	    remote_cmd $h "systemctl restart xinetd"
   815	        remote_cmd $h "systemctl enable xinetd.service"
  1093	            remote_cmd $LB_HOSTNAME "systemctl enable haproxy.service"
  1094	            remote_cmd $LB_HOSTNAME "systemctl start haproxy"
```

**Comment by ashraf-s9s** [comment]
Thanks. s9s_haproxy is a deprecated helper script to deploy HAproxy. We encourage users to deploy HAproxy directly from ClusterControl > Manage > Load Balancer, where CMON internal process has to perform the job.
